# fly.toml app configuration file generated for poe2-pathofcrafting-backend on 2025-10-08T00:37:39+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'poe2-pathofcrafting-backend'
primary_region = 'syd'

[build]
  image = 'ghcr.io/frankthetank001/poe2-pathofcrafting-backend:latest'

[env]
  ENVIRONMENT = 'production'
  PYTHONUNBUFFERED = '1'

[[mounts]]
  source = 'backend_data'
  destination = '/app/data'
  initial_size = '1gb'

[http_service]
  internal_port = 8000
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
